# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='score',
        ),
        migrations.AddField(
            model_name='teacher',
            name='score1',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='score2',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='score3',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='teacher',
            name='score4',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.IntegerField(default=1),
        ),
    ]
