# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20161112_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='score1',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='score2',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='score3',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='score4',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tid',
            field=models.CharField(max_length=20),
        ),
    ]
