# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('passwd', models.CharField(max_length=200)),
                ('u_id', models.DecimalField(decimal_places=10, max_digits=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
